services:
  express-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app # Mount the current directory to /app inside the container
      - /app/node_modules # Prevent conflicts with host node_modules
    command: npm run dev # Use the nodemon dev script